### ISSUE TITLE
Experimental results

### ISSUE THREAD

**Issue by fennudehaogua** [BioAITeam/GBRAS_SW#1]
I feel a little confused about the experimental results in your paper, because there seems to be a big gap compared with the original paper. For example, in the original YeNet, SRNet paper, the data set is Boss+BOW2, and the detection error of WOW at 0.2bpp  are 83.09% and 83.24%. The experimental results in your paper are 73.6% and 79.4%. Can you explain this problem and share your comparative experiment code (including YeNet, SRNet, ZhuNet, YEDROUDJ-NET)?Thank you very much！

**Comment by BioAITeam** [comment]
Hello I hope you are well
When making the reproductions, the results may vary due to the great sensitivity of deep learning in this problem; for example, if you look at the new Zhu-Net article ([link](https://ieeexplore.ieee.org/document/8809687)), you may see results that are not necessarily the same as the other articles. For example, in Ye-Net, SCA is not used...

We proposed improvements to the CNN architectures in the paper ([link](https://doi.org/10.7717/peerj-cs.451)).
Here you will find a repository. In which are the improvements to specific CNN's for steganalysis, and the application of the same strategy to other image classification networks such as VGG16.

I hope this will help.
